Maybe jenkin specific variables are retireved differently
groovy.lang.MissingPropertyException: No such property: PROJECT_NAME for class: groovy.lang.Binding

changing to see if cna resolve