Changing status method call in jenkins all dev build script
testing what would happen if call getResult() instead of status in master script, due to current failure:

groovy.lang.MissingPropertyException: No such property: status for class: groovy.lang.Binding